# Generated by Django 5.0.6 on 2024-05-28 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MusicData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_title', models.CharField(blank=True, max_length=150, null=True)),
                ('music_text', models.TextField(blank=True, null=True)),
                ('music_video_links', models.CharField(blank=True, max_length=1500, null=True)),
            ],
        ),
    ]
