# Generated by Django 5.0.6 on 2024-05-28 17:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicdata',
            name='created_add',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
