# Generated by Django 5.0.6 on 2024-05-31 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_musicdata_created_add'),
    ]

    operations = [
        migrations.RenameField(
            model_name='musicdata',
            old_name='created_add',
            new_name='created_at',
        ),
    ]
