# Generated by Django 5.0.6 on 2024-06-05 13:18

import music.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_musicdata_music_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicdata',
            name='music_file',
            field=models.FileField(blank=True, max_length=50, null=True, unique=True, upload_to='music_file', validators=[music.models.validate_file_size]),
        ),
    ]
