# Generated by Django 5.0.6 on 2024-06-09 12:38

import music.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_musicdata_music_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='musicdata',
            old_name='music_text',
            new_name='lyrics',
        ),
        migrations.AddField(
            model_name='musicdata',
            name='end',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='musicdata',
            name='intro',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='musicdata',
            name='song_language',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='musicdata',
            name='timings',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='musicdata',
            name='music_file',
            field=models.FileField(blank=True, max_length=50, null=True, unique=True, upload_to='music_file', validators=[music.models.validate_file_size, music.models.validate_mp3_file]),
        ),
    ]
