# Generated by Django 5.0.6 on 2024-06-12 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_rename_music_text_musicdata_lyrics_musicdata_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicdata',
            name='artists_social_networks',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='musicdata',
            name='musician_performer',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
