# Generated by Django 5.0.6 on 2024-06-24 14:24

import music.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_musicdata_artists_social_networks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicdata',
            name='music_file',
            field=models.FileField(blank=True, max_length=80, null=True, unique=True, upload_to='music_file', validators=[music.models.validate_file_size, music.models.validate_mp3_file]),
        ),
    ]
